Replaced manual truncates in run() with truncateAll()
spatie/seeders pull request #9
Opened 2017-03-29 08:45 UTC by AlexVanderbist

As described in spatie/blender/issues/299

2017-03-29 09:03 UTC, freekmurze commented on src/DatabaseSeeder.php
> +        Schema::disableForeignKeyConstraints();
Can be replaced with

```php
$tableDropper = TableDropperFactory::create(DB::getDriverName());

$tableDropper->dropAllTables();

DB::reconnect();
```

2017-03-29 09:07 UTC, sebastiandedeyne commented on src/DatabaseSeeder.php
> +        Schema::disableForeignKeyConstraints();
It can't, the TableDropper drops tables, we need to truncate.

2017-03-29 09:18 UTC, freekmurze commented on src/DatabaseSeeder.php
> +        Schema::disableForeignKeyConstraints();
True, sorry for the noise

2017-03-30 07:10 UTC, sebastiandedeyne requested changes

2017-03-30 07:10 UTC, sebastiandedeyne commented on src/DatabaseSeeder.php
> +            ->each(function (string $tableName) {
Could you add an exception for `migrations`?

2017-03-30 07:10 UTC, sebastiandedeyne commented on src/DatabaseSeeder.php
>      protected function truncate(string ...$tables)
Keep this for backwards compat, but mark it as deprecated.

2017-03-30 07:57 UTC, sebastiandedeyne approved these changes

2017-03-30 07:58 UTC, merged

2017-03-30 07:58 UTC, sebastiandedeyne commented
Thanks!